# Generated by Django 5.1.6 on 2025-03-04 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_alter_meal_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('Breakast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), (' Snack', ' Snack')], default='Snack', max_length=100)),
                ('calories', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Name_of_meal', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
